### ISSUE TITLE
Not enough points

### ISSUE THREAD

**Issue by Adskidoodle** [tobygaskell/FPG#12]
Player Adamhatton7 seems to not be getting any points on a week-by-week basis. If anything, his point count is going backwards or standing stagnant per week. Please can you check the code because he should be at least a mid/high table player so there must be an issue somewhere within the game.
I look forward to your speedy response
Thank you

**Comment by tobygaskell** [comment]
I can confirm this is user error and not an issue with the code - thankyou for raising the issue, however to improve on your experience, I recommend you ask Maxine Carroll for her predictions. Thankyou
